version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Maps port 3000 on the host to port 80 in the container
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Maps port 5000 on the host to port 5000 in the container
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/app

